### ISSUE TITLE
Cannot read property 'cc' of undefined

### ISSUE THREAD

**Issue by tgr** [vivliostyle/vivliostyle.js#368]
Trying to render the Wikipedia article Climate of Australia results in the error message `Cannot read property 'cc' of undefined`. [Test page](http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://en.wikipedia.org/api/rest_v1/page/html/Climate_of_Australia) (using the vivliostyle.github.io installation with Chrome version 59.0.3071.86 (64-bit official build) on Ubuntu 16.04) - rendering is cut off somewhere in the [Victoria](https://en.wikipedia.org/wiki/Climate_of_Australia#Victoria) section. (Using a local installation with different layout settings gets a few lines further but still not to the end of the section.) The full error message, as provided by Chrome:

<pre>
TypeError: Cannot read property 'cc' of undefined
    at Yv (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:342384)
    at Qv.Nf (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:342956)
    at Qv.n.kd (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:152937)
    at gm.<anonymous> (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:152355)
    at http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:35613
    at b (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:35339)
    at oe (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:35456)
    at pe (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:35551)
    at hm (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:152200)
    at hw (http://vivliostyle.github.io/vivliostyle.js/viewer/js/main.js:7769:345803)
	---- async ---
	startTableCell
	loop
	Frame.loop
	LayoutIterator
	TableFormattingContext.doLayout
	vivliostyle.layoututil.AbstractLayoutRetryer.tryLayout
	vivliostyle.layoututil.AbstractLayoutRetryer.tryLayout
	layoutNext
	loop
	Frame.loop
	doLayout
	adapt.layout.DefaultLayoutMode.doLayout
	vivliostyle.layoututil.AbstractLayoutRetryer.tryLayout
	layout
	loop
	Frame.loop
	layoutColumn
	loop
	Frame.loop
	createAndLayoutColumn
	loop
	Frame.loop
	layoutContainer.inner
	layoutContainer
	AsyncResult.thenAsync
	Frame.loop
	layoutContainer
	loop
	Frame.loop
	layoutNextPage
	renderSinglePage
	loop
	Frame.loop
	renderPage
	loop
	Frame.loop
	renderAllPages
	resize
</pre>

**Comment by tgr** [comment]
[Test page with permalink to Wikipedia article revision](http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://en.wikipedia.org/api/rest_v1/page/html/Climate_of_Australia/788338331/3970b048-5de0-11e7-9c61-1f14ac97ede2).

**Comment by kwkbtr** [comment]
Thank you for the report.
It seems that our implementation has a problem handling a table nested inside another table.
We will look into the problem further.

**Comment by MurakamiShinyu** [comment]
Could not see the problem now. It seems already fixed.
