### ISSUE TITLE
Formulae inside a Table of Fiduswriter

### ISSUE THREAD

**Issue by regostar** [vivliostyle/vivliostyle.js#465]
When formulae are inserted in table of fiduswriter, the pdf is not at all generated. 
![formulae](https://user-images.githubusercontent.com/26195098/48753048-458cf680-ecb2-11e8-9083-079fdf640295.png)
There is an error message on the console :- 
![error](https://user-images.githubusercontent.com/26195098/48753097-8ab12880-ecb2-11e8-89b0-dc46e74d753a.png)

(TypeError: Cannot read property 'b' of undefined 
 TypeError: Cannot read property 'b' of undefined
    at cx (https://staging.fiduswriter.org/static/js/transpile/app.js?v=1541062861:120349:178)
    at Vw.fg (https://staging.fiduswriter.org/static/js/transpile/app.js?v=1541062861:120350:267))

**Comment by MurakamiShinyu** [comment]
We can't reproduce the problem without the source data. Please attach the source data (in Fidus Writer, `Export > HTML`).

**Comment by regostar** [comment]
[formula.zip](https://github.com/vivliostyle/vivliostyle.js/files/2610606/formula.zip)

**Comment by regostar** [comment]
[formula.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/2610641/formula.html.zip)

**Comment by MurakamiShinyu** [comment]
I am investigating the problem.

The error message on the debug mode is as follows:

```
 TypeError: Cannot read property 'anchorSlot' of undefined
    at vivliostyle.table.TableLayoutStrategy.TableLayoutStrategy.startTableCell (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/vivliostyle/table.js:1126:43)
    at vivliostyle.table.TableLayoutStrategy.TableLayoutStrategy.startNonInlineBox (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/vivliostyle/table.js:1174:25)
    at vivliostyle.table.TableLayoutStrategy.EdgeSkipper.startNonInlineElementNode (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/vivliostyle/layoututil.js:308:21)
    at frame.loopWithFrame.loopFrame (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/vivliostyle/layoututil.js:166:42)
    at loop (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/adapt/task.js:927:13)
    at adapt.task.LoopBodyFrame.step [as callback] (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/adapt/task.js:892:32)
    at adapt.task.LoopBodyFrame.adapt.task.Frame.finish (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/adapt/task.js:792:18)
    at adapt.task.LoopBodyFrame.continueLoop (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/adapt/task.js:965:10)
    at adapt.task.Frame.nextResult.then.nextNodeContext [as callback] (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/vivliostyle/layoututil.js:183:39)
    at adapt.task.Frame.finish (http://localhost:3000/vivliostyle-ui/node_modules/vivliostyle/src/adapt/task.js:792:18)
	---- async ---
…
```

I found this problem occurs when page breaking happens inside a table cell that contains an element with display: inline-table.
(In the formulae generated by Fidus Writer with the katex library, `display: inline-table` is used for fraction notation)

I wrote simplified test samples on https://gist.github.com/MurakamiShinyu/e2d99fe498b3de5f280371d40241dc93.

Test with the online Vivliostyle Viewer:
- test1: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://gist.githack.com/MurakamiShinyu/e2d99fe498b3de5f280371d40241dc93/raw/5418ec6fc372101c547b8dcf61664787cb623aaa/test1.html&spread=false
- test2: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://gist.githack.com/MurakamiShinyu/e2d99fe498b3de5f280371d40241dc93/raw/5418ec6fc372101c547b8dcf61664787cb623aaa/test2.html&spread=false

Debug on local machine (`npm run serve-dev` with vivliostyle-ui, see https://github.com/vivliostyle/vivliostyle.js/wiki/Development)
- test1: http://localhost:3000/vivliostyle-ui/build/vivliostyle-viewer-dev.html#debug=true&x=https://gist.githack.com/MurakamiShinyu/e2d99fe498b3de5f280371d40241dc93/raw/5418ec6fc372101c547b8dcf61664787cb623aaa/test1.html&spread=false
- test2: http://localhost:3000/vivliostyle-ui/build/vivliostyle-viewer-dev.html#debug=true&x=https://gist.githack.com/MurakamiShinyu/e2d99fe498b3de5f280371d40241dc93/raw/5418ec6fc372101c547b8dcf61664787cb623aaa/test2.html&spread=false

**Comment by MurakamiShinyu** [comment]
Fixed the bug.

The pre-release version [2018.10.101-pre.20181221160257](https://www.npmjs.com/package/vivliostyle/v/2018.10.101-pre.20181221160257) includes this fix.
